# Generated by Django 2.0.7 on 2019-04-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20180806_0653")]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="email",
            field=models.EmailField(default="", max_length=254),
        )
    ]
